version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"  # Alleen voor development!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - seosea_network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile.dev
    volumes:
      - ./src/frontend:/app/src/frontend
      - ./public:/app/public
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://api.localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - seosea_network
    depends_on:
      - api

  dashboard:
    build:
      context: .
      dockerfile: dashboard.Dockerfile.dev
    volumes:
      - ./src/dashboard:/app/src/dashboard
      - dashboard_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://api.localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.localhost`)"
      - "traefik.http.services.dashboard.loadbalancer.server.port=3001"
    networks:
      - seosea_network
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - api_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongodb:27017/seo-sea?authSource=admin
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
    networks:
      - seosea_network
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  mongodb:
    image: mongo:6
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - seosea_network

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - seosea_redis:/data
    networks:
      - seosea_network

networks:
  seosea_network:
    driver: bridge

volumes:
  seosea_mongodb:
  seosea_redis:
  frontend_node_modules:
  dashboard_node_modules:
  api_node_modules:
  mongodb_data:
