FROM node:20-alpine

# Installeer Chrome dependencies
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont

# Zet Puppeteer om Chromium te gebruiken
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

WORKDIR /app

# Kopieer package.json
COPY package.json ./

# Schone installatie zonder package-lock
RUN npm install --no-package-lock --production && \
    npm install --no-package-lock --save-dev

# Kopieer de rest van de applicatie
COPY . .

# Start de applicatie
CMD ["npm", "run", "dev"]
